export enum EVENT_TYPES {
    NEW_USER_EVENT = "NEW_USER_EVENT",
    ASSIGN_USER_ID_EVENT = "ASSIGN_USER_ID_EVENT",
    USER_MOVE_EVENT = "USER_MOVE_EVENT",
    KEYBOARD_EVENT = "KEYBOARD_EVENT",
    PLAYER_TARGET_POSITION_EVENT = "PLAYER_TARGET_POSITION_EVENT",
    RESOURCE_POSITIONS_EVENT = "RESOURCE_POSITIONS_EVENT",
    REMOVE_PLAYER_EVENT = "REMOVE_PLAYER_EVENT",
    HIT_RESOURCE_EVENT = "HIT_RESOURCE_EVENT",
    UPDATE_RESOURCE_EVENT = "UPDATE_RESOURCE_EVENT",
    LOOT_RESOURCE_EVENT = "LOOT_RESOURCE_EVENT",
    PLAYER_PLACED_RESOURCE_EVENT = "PLAYER_PLACED_RESOURCE_EVENT",
    LOAD_INVENTORY_EVENT = "LOAD_INVENTORY_EVENT",
    UPDATE_INVENTORY_EVENT = "UPDATE_INVENTORY_EVENT",
}

export const SCREEN_SIZE = 750