/* export enum EVENT_TYPES {
    NEW_USER_EVENT = "NEW_USER_EVENT",
    ASSIGN_USER_ID_EVENT = "ASSIGN_USER_ID_EVENT",
    USER_MOVE_EVENT = "USER_MOVE_EVENT",
    KEYBOARD_EVENT = "KEYBOARD_EVENT",
    PLAYER_TARGET_POSITION_EVENT = "PLAYER_TARGET_POSITION_EVENT",
    RESOURCE_POSITIONS_EVENT = "RESOURCE_POSITIONS_EVENT",
    REMOVE_PLAYER_EVENT = "REMOVE_PLAYER_EVENT",
    HIT_RESOURCE_EVENT = "HIT_RESOURCE_EVENT",
    UPDATE_RESOURCE_EVENT = "UPDATE_RESOURCE_EVENT",
    LOOT_RESOURCE_EVENT = "LOOT_RESOURCE_EVENT",
    PLAYER_PLACED_RESOURCE_EVENT = "PLAYER_PLACED_RESOURCE_EVENT",
    LOAD_INVENTORY_EVENT = "LOAD_INVENTORY_EVENT",
    UPDATE_INVENTORY_EVENT = "UPDATE_INVENTORY_EVENT",
    REMOVE_GRID_CELL = "REMOVE_GRID_CELL"
} */

export enum EVENT_TYPES {
    NEW_USER_EVENT = 0,
    ASSIGN_USER_ID_EVENT = 1,
    USER_MOVE_EVENT = 2,
    KEYBOARD_EVENT = 3,
    PLAYER_TARGET_POSITION_EVENT = 4,
    RESOURCE_POSITIONS_EVENT = 5,
    REMOVE_PLAYER_EVENT = 6,
    HIT_RESOURCE_EVENT = 7,
    UPDATE_RESOURCE_EVENT = 8,
    LOOT_RESOURCE_EVENT = 9,
    PLAYER_PLACED_RESOURCE_EVENT = 10,
    LOAD_INVENTORY_EVENT = 11,
    UPDATE_INVENTORY_EVENT = 12,
    REMOVE_GRID_CELL = 13,
    MULTIPLE_EVENTS = 14,
}

export const SCREEN_SIZE = 750