export enum EVENT_TYPES {
    NEW_USER_EVENT = "NEW_USER_EVENT",
    ASSIGN_USER_ID_EVENT = "ASSIGN_USER_ID_EVENT",
    USER_MOVE_EVENT = "USER_MOVE_EVENT",
    KEYBOARD_EVENT = "KEYBOARD_EVENT",
    PLAYER_TARGET_POSITION_EVENT = "PLAYER_TARGET_POSITION_EVENT",
    RESOURCE_POSITIONS_EVENT = "RESOURCE_POSITIONS_EVENT",
    PLAYER_DISCONNECTED_EVENT = "PLAYER_DISCONNECTED_EVENT"
}

export const playerFrames = ["player0.png", "player1.png", "player2.png", "player3.png"]

export enum ASSETS {
    Iron = "iron.png"
}